apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lwoy
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0017-tenant/tkrw-pr712-0075-0017-app/devfile-sample-lwoy@sha256:59f978a26b954362222f0367b972818c4258fc55f42078001bd2f2ff19a1f1d9
        name: my-nodejs
        resources: {}
status: {}
